---
all:
  children:
    libvirt:
      hosts:
        libvirt:
          ansible_host: vagrant_server
    cloud:
      hosts:
        libvirt:
          ansible_host: vagrant_server
        hetzner_vm:
          ansible_host: vagrant_hetzner_vm
    local:
      hosts:
        local_server:
          ansible_host: vagrant_local_vm
    kubernetes:
      hosts:
        hetzner_vm:
          ansible_host: vagrant_hetzner_vm
        local_vm:
          ansible_host: vagrant_local_vm
    kubernetes_master:
      hosts:
        hetzner_vm:
          ansible_host: vagrant_hetzner_vm

...
