---
all:
  children:
    libvirt:
      hosts:
        hetzner_libvirt:
          ansible_host: hetzner_server
        local_libvirt:
          ansible_host: local_server
    cloud:
      hosts:
        hetzner_libvirt:
          ansible_host: hetzner_server
        hetzner_vm:
          ansible_host: hetzner_vm
    local:
      hosts:
        local_libvirt:
          ansible_host: local_server
        local_vm:
          ansible_host: local_vm
    kubernetes:
      hosts:
        hetzner_vm:
          ansible_host: hetzner_vm
        local_vm:
          ansible_host: local_vm
      vars:
        ansible_ssh_transfer_method: piped # Fixes warnings about ssh transfer method
    kubernetes_master:
      hosts:
        hetzner_vm:
          ansible_host: hetzner_vm

...
