---
k3s_role: master
# k3s_extra_server_args: "--node-ip 192.168.150.1 --node-external-ip 192.168.150.1 --flannel-iface wg0 --node-label location=cloud"

k3s_kubeconfig_local_dest: ~/.kube/homelab-cloud.yaml
kubeconfig: "{{ k3s_kubeconfig_local_dest }}"

wireguard_ip: "192.168.150.1/24"

wireguard_private_key: "{{ vault_wireguard_private_key }}"

wireguard_additional_peers: "{{ vault_wireguard_additional_peers }}"
...
