---
- name: Expand disk space
  hosts: kubernetes
  become: true
  handlers:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 600

  tasks:
    - name: Check if transactional-update state is present
      become: true
      ansible.builtin.stat:
        path: /var/lib/misc/transactional-update.state
      register: transactional_update_state

    - name: Touch transactional update state
      become: true
      ansible.builtin.file:
        path: /var/lib/misc/transactional-update.state
        state: touch # Needed for Ansible to detect transactional-update is required...
      when: not transactional_update_state.stat.exists

    - name: Install open-isci
      become: true
      community.general.zypper:
        name: open-iscsi
        state: present
        update_cache: true
      notify: Reboot host

    - name: Install disk util dependencies
      become: true
      community.general.zypper:
        name:
          - btrfs-progs
          - parted
          - python310-pexpect
        state: present
        update_cache: true
      notify: Reboot host

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Expand /dev/vda4 partition
      become: true
      ansible.builtin.expect: # parted modue doesn't work properly with mounted filesystems
        command: parted /dev/vda resizepart
        responses:
          'Partition number.*': '4'
          'Fix/Ignore.*': 'Fix'
          'End.*': '100%'
          'Yes/No.*': 'yes'
        echo: true
        timeout: 30

    - name: Resize partition
      become: true
      community.general.filesystem:
        dev: /dev/vda4
        resizefs: true
        fstype: btrfs

- name: Set up Wireguard tunnel
  hosts: kubernetes
  roles:
    - { role: diademiemi.wireguard, tags: ['wireguard', 'k3s-prepare'] }
...
