---
- name: Install K3S
  hosts: hetzner_vm
  roles:
    - { role: diademiemi.k3s, tags: ['k3s', 'k3s-cluster'] }

- name: Install K3S
  hosts: local_vm
  roles:
    - { role: diademiemi.k3s, tags: ['k3s', 'k3s-cluster'] }
...
