---
- name: Install K3S
  hosts: kubernetes
  pre_tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"
      when: new_hostname is defined

  roles:
    - { role: diademiemi.k3s, tags: ['k3s', 'k3s-cluster'] }
...
