---
- name: Set up ArgoCD
  hosts: kubernetes_master
  tasks:
    - name: Set up ArgoCD
      environment:
        KUBECONFIG: "{{ kubeconfig | default('~/.kube/config') }}"
      delegate_to: localhost
      block:
        - name: Patch ArgoCD Repo server
          kubernetes.core.k8s:
            state: patched
            merge_type: strategic-merge
            definition:
              apiVersion: v1
              kind: Node
              metadata:
                name: "{{ item.node }}"
                annotations:
                  node.longhorn.io/default-node-tags: '[\"{{ item.tag }}\"]'

          loop: "{{ longhorn_tags }}"
          when: longhorn_tags is defined
...
